# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{enchant}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paolo Perego"]
  s.date = %q{2010-05-19}
  s.default_executable = %q{enchant}
  s.description = %q{Enchant is tool aimed to discover web application directory and pages by fuzzing the requests using a dictionary approach}
  s.email = %q{paolo@armoredcode.com}
  s.executables = ["enchant"]
  s.extra_rdoc_files = [
    "ChangeLog",
     "README.txt"
  ]
  s.files = [
    ".gitignore",
     "COPYING",
     "ChangeLog",
     "README.txt",
     "Rakefile",
     "VERSION",
     "bin/enchant",
     "enchant.gemspec",
     "lib/enchant.rb",
     "test/test_enchant.rb"
  ]
  s.homepage = %q{http://github.com/thesp0nge/enchant}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Your magical web application fuzzer}
  s.test_files = [
    "test/test_enchant.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruby-progressbar>, [">= 0"])
    else
      s.add_dependency(%q<ruby-progressbar>, [">= 0"])
    end
  else
    s.add_dependency(%q<ruby-progressbar>, [">= 0"])
  end
end

